#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  limit,          sensorTouch)
#pragma config(Sensor, I2C_1,  rightFlywheel,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftFlywheel,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;

float right_encoder;
float left_encoder;

float right_rpm;
float left_rpm;

float mainBattery;
float backupBattery;

task main()
{
	resetMotorEncoder(rightFront);
	resetMotorEncoder(leftFront);

	clearLCDLine(0);
	clearLCDLine(1);

	bool left = false;
	bool center = true;
	bool right = false;

	clearLCDLine(0);

	while(true)
	{
		if(right_rpm >= 100)
			clearLCDLine(1);
		if(left_rpm >= 100)
			clearLCDLine(1);

		motor[rightFront] = 127;
		motor[leftFront] = 127;

		right_encoder = nMotorEncoder[rightFront];
		left_encoder = nMotorEncoder[leftFront];

		right_rpm = getMotorVelocity(rightFront);
		left_rpm = getMotorVelocity(leftFront);

		mainBattery = nImmediateBatteryLevel/100000.0;
		backupBattery = BackupBatteryLevel/100000.0;

		if(nLCDButtons == leftButton)
		{
			left = true;
			center = false;
			right = false;
		}
		else if(nLCDButtons == centerButton)
		{
			left = false;
			center = true;
			right = false;
		}
		else if(nLCDButtons == rightButton)
		{
			left = false;
			center = false;
			right = true;
		}

		if(left)
		{
			displayLCDCenteredString(0, "Left   Right");
			displayLCDNumber(1, 0, left_encoder);
			displayLCDNumber(1, 8, right_encoder);
		}
		else if(center)
		{
			displayLCDCenteredString(0, "Left   Right");
			displayLCDNumber(1, 0, left_rpm);
			displayLCDNumber(1, 8, right_rpm);
		}
		else if(right)
		{
			displayLCDCenteredString(0, "Main   Backup");
			displayLCDNumber(1, 0, mainBattery);
			displayLCDNumber(1, 8, backupBattery);
		}
	}
}
