#pragma config(I2C_Usage,	I2C1,	i2cSensors)
#pragma config(Sensor,	dgtl1,	LED,		sensorLEDtoVCC)
#pragma config(Sensor,	I2C_1,	,			sensorQuadEncoderOnI2CPort,	,	AutoAssign)
#pragma config(Sensor,	I2C_2,	,			sensorQuadEncoderOnI2CPort,	,	AutoAssign)
#pragma config(Motor,	port2,	rightBack,	tmotorVex393HighSpeed_MC29,	openLoop,	reversed, encoderPort, I2C_1)
#pragma config(Motor,	port3,	rightFront,	tmotorVex393HighSpeed_MC29,	openLoop,	reversed)
#pragma config(Motor,	port4,	intakeHigh,	tmotorVex393_MC29,			openLoop)
#pragma config(Motor,	port5,	RightDrive,	tmotorVex393_MC29,			openLoop,	reversed,	driveRight)
#pragma config(Motor,	port6,	LeftDrive,	tmotorVex393_MC29,			openLoop,	driveLeft)
#pragma config(Motor,	port7,	intakeLow,	tmotorVex393_MC29,			openLoop,	reversed)
#pragma config(Motor,	port8,	leftBack,	tmotorVex393HighSpeed_MC29, openLoop,	encoderPort,	I2C_2)
#pragma config(Motor,	port9,	leftFront,	tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define PID_kP	0.02
#define PID_kI	0.04

task main()
{
	double pidError_Right = 0;
	double pidIntegral_Right = 0;
	double pidValue_Right;

	double pidError_Left = 0;
	double pidIntegral_Left = 0;
	double pidValue_Left;

	double speed_Right = 0;
	double speed_Left = 0;
	
	while(true)
	{
		pidError_Right = DESIRED_RPM_FLYWHEEL - RPM_RIGHT_FLYWHEEL;
		pidError_Left = DESIRED_RPM_FLYWHEEL - RPM_LEFT_FLYWHEEL;

		if(pidError_Right < 50)
			pidIntegral_Right += pidError_Right;
		else
			pidIntegral_Right = 0;

		if(pidError_Left < 50)
			pidIntegral_Left += pidError_Left;
		else
			pidIntegral_Left = 0;
		
		pidValue_Right = (kP*pidError_Right)+(kI*pidIntegral_Right);
		speed += pidValue_Right;

		pidValue_Left = (kP*pidError_Left)+(kI*pidIntegral_Left);
		speed += pidValue_Left;
		
		if(speed_Right > 127)
			speed_Right = 127;
		if(speed_Right < -127)
			speed_Right = -127;

		if(speed_Left > 127)
			speed_Left = 127;
		if(speed_Left < -127)
			speed_Left = -127;

		motor[rightFront]   = speed_Right;
		motor[rightBack] = speed_Right;
		motor[leftFront]   = speed_Left;
		motor[leftBack] = speed_Left;
	}
}