#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightDrive,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           LeftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DESIRED_RPM_MOTOR 107
#define DESIRED_RPM_FLYWHEEL 1928

int time;
float RPM_Right_Motor, RPM_Right_FlyWheel;
task main()
{
//	float fast = 120,
//	float med = 90,
	float slow = 65;
//	float low = 50;

	resetMotorEncoder(leftBack);
	resetMotorEncoder(rightBack);

	clearTimer(T1);

	while(true)
	{

		RPM_Right_Motor = getMotorVelocity(rightBack);
		RPM_Right_FlyWheel = RPM_Right_Motor * 18;

//		motor[intakeLow] = 127;
//		motor[intakeHigh] = 127;
		time = time1[T1];

		if(time % 10000 == 0)
			slow-=1;

		motor[rightFront]   = slow;
		motor[rightBack] = slow;

		motor[leftFront]   = slow;
		motor[leftBack] = slow;

//		SensorValue[LED] = RPM_Right_FlyWheel > DESIRED_RPM_FLYWHEEL && RPM_Left_FlyWheel > DESIRED_RPM_FLYWHEEL;
	}
}
