#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  shaftEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  shaftEncoderRight, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int fast = 127;
	int med = 90;
	int slow = 70;
	int low = 50;
/*
	motor[leftFront]  = 0;
	motor[leftBack]   = 0;
	motor[rightFront] = 0;
	motor[rightBack] = 0;
*/	
	motor[leftFront]  = slow;
	motor[leftBack]   = slow;
	motor[rightFront] = slow;
	motor[rightBack] = slow;
	
/*	
	motor[leftFront] = med;
	motor[leftBack] = med;
	motor[rightFront] = med;
	motor[rightBack] = med;
*/
/*
	motor[rightFront] = fast;
	motor[rightBack] = fast;
	motor[leftFront] = fast;
	motor[leftBack] = fast;
*/
/*	
	motor[rightFront] = low;
	motor[rightBack] = low;
	motor[leftFront] = low;
	motor[leftBack] = low;
*/	
	while(true);
}
