#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  shaftEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  shaftEncoderRight, sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port1,           rightDrive,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	int speed = 55;

	motor[leftBack]   = speed;
	motor[leftFront]  = speed;
	motor[rightFront] = speed;
	motor[rightBack]  = speed;
	wait1Msec(2500);
	motor[intakeLow]  = 127;
	motor[intakeHigh] = 127;

	wait1Msec(100000);

	motor[leftBack]   = 0;
	motor[leftFront]  = 0;
	motor[rightFront] = 0;
	motor[rightBack]  = 0;

	motor[intakeLow]  = 0;
	motor[intakeHigh] = 0;
}

task usercontrol()
{
	while(true)
	{
		motor[leftDrive] = vexRT[Ch3];       //Drive motors left
		motor[rightDrive] = vexRT[Ch2];      //Drive motors right
			if(vexRT[Btn7U])
			motor[intakeLow] = 127;   //intake Low - Button 7U
		else if(vexRT[Btn7L])
			motor[intakeLow] = -127;  //reverse - Button 7L
		else if(vexRT[Btn7D])
			motor[intakeLow] = 0;     //off - Button 7D

		if(vexRT[Btn5U])
			motor[intakeHigh] = 127;  //intake High (Lift) - Button 5U
		else if(vexRT[Btn7R])
			motor[intakeHigh] = -127; //reverse - Button 7R
		else if(vexRT[Btn5D])
			motor[intakeHigh] = 0;    //off - Button 5D

		if(vexRT[Btn6D]) //Button 6D - flywheels OFF
		{
			motor[leftFront]  = 0;
			motor[leftBack]   = 0;
			motor[rightFront] = 0;
			motor[rightBack] = 0;
		}
		if(vexRT[Btn6U]) //Button 6U - flywheels 63
		{
			motor[leftFront]  = 63;
			motor[leftBack]   = 63;
			motor[rightFront] = 63;
			motor[rightBack] = 63;
		}
		if(vexRT[Btn8U]) //Button 8U - flywheels 90
		{
			motor[leftFront] = 90;
			motor[leftBack] = 90;
			motor[rightFront] = 90;
			motor[rightBack] = 90;
		}
	 	if(vexRT[Btn8L]) //Button 8L - flywheels 40
		{
			motor[rightFront] = 40;
			motor[rightBack] = 40;
			motor[leftFront] = 40;
			motor[leftBack] = 40;
		}
		if(vexRT[Btn8D]) //Button 8D - flywheels 39
		{
			motor[rightFront] = 39;
			motor[rightBack] = 39;
			motor[leftFront] = 39;
			motor[leftBack] = 39;
		}
	}
}

