#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  shaftEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  shaftEncoderRight, sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port1,           rightDrive,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	int speed = 55;

	motor[leftBack]   = speed;
	motor[leftFront]  = speed;
	motor[rightFront] = speed;
	motor[rightBack]  = speed;
	wait1Msec(2500);
	motor[intakeLow]  = 127;
	motor[intakeHigh] = 127;

	wait1Msec(100000);

	motor[leftBack]   = 0;
	motor[leftFront]  = 0;
	motor[rightFront] = 0;
	motor[rightBack]  = 0;

	motor[intakeLow]  = 0;
	motor[intakeHigh] = 0;
}

task usercontrol()
{
	int flag = 0, speed = 52;

	while(true)
	{
		motor[leftDrive]  = vexRT[Ch3];
		motor[rightDrive] = vexRT[Ch2];

		if(flag == 1)
		{
			if(vexRT[Btn8R])
			{
				motor[leftFront]  = 35;
				motor[leftBack]   = 35;
				motor[rightFront] = 35;
				motor[rightFront] = 35;
			}
			if(vexRT[Btn8L])
			{
				motor[leftFront]  = 52;
				motor[leftBack]   = 52;
				motor[rightFront] = 52;
				motor[rightBack]  = 52;
			}
		}

	 	if(vexRT[Btn6U])
		{
			flag = 1;

			motor[rightFront] = speed;
			motor[rightBack]  = speed;
			motor[leftFront]  = speed;
			motor[leftBack]   = speed;
		}
		else if(vexRT[Btn6D])
		{
			flag = 0;

			motor[rightFront] = 0;
			motor[rightBack]  = 0;
			motor[leftFront]  = 0;
			motor[leftBack]   = 0;
		}

		if(vexRT[Btn7U])
			motor[intakeLow] = 127;
		else if(vexRT[Btn7L])
			motor[intakeLow] = -127;
		else if(vexRT[Btn7D])
			motor[intakeLow] = 0;

		if(vexRT[Btn5U])
			motor[intakeHigh] = 127;
		else if(vexRT[Btn7R])
			motor[intakeHigh] = -127;
		else if(vexRT[Btn5D])
			motor[intakeHigh] = 0;
	}
}
