#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightDrive,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           LeftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
void turnAngle(float angle)
{
	int speed = 63;

	while(SensorValue[gyro] < SensorValue[gyro]+(10*angle))
	{
		if(angle < 0)
		{
			motor[rightMotor] = -speed;
			motor[leftMotor] = speed;
		}
		else if(angle > 0)
		{
			motor[rightMotor] = speed;
			motor[leftMotor] = -speed;
		}
	}
}
*/
#define ncdrCtPRev 392
#define waitTime 10

float m1, m2, ecs, rpm;

float getRPM1()
{
	m1 = getMotorEncoder(rightBack);
	wait1Msec(waitTime);
	m2 = getMotorEncoder(rightBack);

	ecs = abs(m2 - m1) / waitTime;
	rpm = (ecs * 1000 * 60) / ncdrCtPRev;

	return rpm;
}

float getRPM2()
{
	m1 = getMotorEncoder(leftBack);
	wait1Msec(waitTime);
	m2 = getMotorEncoder(leftBack);

	ecs = abs(m2 - m1) / waitTime;
	rpm = (ecs * 1000 * 60) / ncdrCtPRev;

	return rpm;
}

// Good RPM is 120
task main()
{
	float
		fast = 120,
		med = 90,
		slow = 70,
		low = 50,

		RPM = 120,

		diff,
		change = 0.1;

	resetMotorEncoder(leftBack);
	resetMotorEncoder(rightBack);

	clearLCDLine(0);
	displayLCDCenteredString(0, "Left     Right");

	while(true)
	{

		motor[intakeLow] = 127;
		motor[intakeHigh] = 127;

		/*diff = RPM - getRPM2();

		if(abs(diff) < 20)
		{
			if(getRPM1() < RPM)
				med+=change;
			else if(getRPM1() > RPM)
				med-=change;

			if(getRPM2() < RPM)
				med+=change;
			else if(getRPM2() > RPM)
				med-=change;
		}*/

		motor[rightFront]   = med;
		motor[rightBack] = med;
		motor[leftFront]   = med;
		motor[leftBack] = med;

		clearLCDLine(1);
		displayLCDNumber(1, 0, getRPM2());
		displayLCDNumber(1, 10, getRPM1());
	}
}
