#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  shaftEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  shaftEncoderRight, sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port1,           rightDrive,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	get into position:
		turn left
	shoot:
		turn on intake
		turn on the fly wheels
*/

task main()
{/*
	motor[rightDrive] = -127;
	motor[leftDrive]  = 127;
	wait1Msec(250);
	motor[rightDrive] = 0;
	motor[leftDrive]  = 0;
*/
	int speed = 55;

	motor[leftBack]   = speed;
	motor[leftFront]  = speed;
	motor[rightFront] = speed;
	motor[rightBack]  = speed;
	wait1Msec(2500);
	motor[intakeLow]  = 127;
	motor[intakeHigh] = 127;

	wait1Msec(100000);

	motor[leftBack]   = 0;
	motor[leftFront]  = 0;
	motor[rightFront] = 0;
	motor[rightBack]  = 0;

	motor[intakeLow]  = 0;
	motor[intakeHigh] = 0;
}
