#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  shaftEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  shaftEncoderRight, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	int speed = 85;

	motor[leftBack]   = speed;
	motor[leftFront]  = speed;
	motor[rightFront] = speed;
	motor[rightBack]  = speed;
	wait1Msec(2500);
	motor[intakeLow]  = 127;
	motor[intakeHigh] = 127;

	wait1Msec(100000);

	motor[leftBack]   = 0;
	motor[leftFront]  = 0;
	motor[rightFront] = 0;
	motor[rightBack]  = 0;

	motor[intakeLow]  = 0;
	motor[intakeHigh] = 0;
}

task usercontrol()
{
	int fast = 127;
	int med = 90;
	int slow = 70;
	int low = 50;

	while(true)
	{
		motor[LeftDrive] = vexRT[Ch3];       //Drive motors left
		motor[RightDrive] = vexRT[Ch2];      //Drive motors right

		if(vexRT[Btn7U])
			motor[intakeLow] = 127;   //intake Low - Button 7U
		else if(vexRT[Btn7L])
			motor[intakeLow] = -127;  //reverse - Button 7L
		else if(vexRT[Btn7D])
			motor[intakeLow] = 0;     //off - Button 7D

		if(vexRT[Btn5U])
			motor[intakeHigh] = 127;  //intake High (Lift) - Button 5U
		else if(vexRT[Btn7R])
			motor[intakeHigh] = -127; //reverse - Button 7R
		else if(vexRT[Btn5D])
			motor[intakeHigh] = 0;    //off - Button 5D

		if(vexRT[Btn6D]) //Button 6D - flywheels OFF
		{
			motor[leftFront]  = 0;
			motor[leftBack]   = 0;
			motor[rightFront] = 0;
			motor[rightBack] = 0;
		}
		if(vexRT[Btn6U]) //Button 6U - flywheels 63
		{
			motor[leftFront]  = slow;
			motor[leftBack]   = slow;
			motor[rightFront] = slow;
			motor[rightBack] = slow;
		}
		if(vexRT[Btn8U]) //Button 8U - flywheels 90
		{
			motor[leftFront] = med;
			motor[leftBack] = med;
			motor[rightFront] = med;
			motor[rightBack] = med;
		}
	 	if(vexRT[Btn8L]) //Button 8L - flywheels 127
		{
			motor[rightFront] = fast;
			motor[rightBack] = fast;
			motor[leftFront] = fast;
			motor[leftBack] = fast;
		}
		if(vexRT[Btn8D]) //Button 8D - flywheels 39
		{
			motor[rightFront] = low;
			motor[rightBack] = low;
			motor[leftFront] = low;
			motor[leftBack] = low;
		}
	}
}
