#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  shaftEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  shaftEncoderRight, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

#define DESIRED_RPM_MOTOR 107
#define DESIRED_RPM_FLYWHEEL 1928

float RPM_Right_Motor;
float RPM_Left_Motor;

float RPM_Right_FlyWheel;
float RPM_Left_FlyWheel;

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;

float right_encoder;
float left_encoder;

float mainBattery;
float backupBattery;


void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	int speed = 85;

	motor[leftBack]   = speed;
	motor[leftFront]  = speed;
	motor[rightFront] = speed;
	motor[rightBack]  = speed;
	
	wait1Msec(2500);
	
	motor[intakeLow]  = 127;
	motor[intakeHigh] = 127;

	wait1Msec(100000);

	motor[leftBack]   = 0;
	motor[leftFront]  = 0;
	motor[rightFront] = 0;
	motor[rightBack]  = 0;

	motor[intakeLow]  = 0;
	motor[intakeHigh] = 0;
}

/*
Right Joystick: Drive right motors
Left Joystick: Drive left motors
Button 7U: Low intake
Button 7L: Low intake reverse
Button 7D: Low intake off
Button 5U: High intake
Button 7R: reverse
Button 5D: High intake off
Button 6D - flywheels off
Button 8D - flywheels 50
Button 6U - flywheels 70
Button 8U - flywheels 90
Button 8L - flywheels 120
*/

task usercontrol()
{
	int fast = 120;
	int med = 90;
	int slow = 70;
	int low = 50;
	
	resetMotorEncoder(leftBack);
	resetMotorEncoder(rightBack);
	
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "Left   Right");

	bool left = false;
	bool center = true;
	bool right = false;
	
	while(true)
	{
		RPM_Right_Motor = getMotorVelocity(rightBack);
		RPM_Right_FlyWheel = RPM_Right_Motor * 18;

		RPM_Left_Motor = getMotorVelocity(leftBack);
		RPM_Left_FlyWheel = RPM_Left_Motor * 18;

		right_encoder = nMotorEncoder[rightFront];
		left_encoder = nMotorEncoder[leftFront];

		mainBattery = nImmediateBatteryLevel/100000.0;
		backupBattery = BackupBatteryLevel/100000.0;
		
		motor[LeftDrive] = vexRT[Ch3];
		motor[RightDrive] = vexRT[Ch2];

		if(vexRT[Btn7U])
			motor[intakeLow] = 127;
		else if(vexRT[Btn7L])
			motor[intakeLow] = -127;
		else if(vexRT[Btn7D])
			motor[intakeLow] = 0;

		if(vexRT[Btn5U])
			motor[intakeHigh] = 127;
		else if(vexRT[Btn7R])
			motor[intakeHigh] = -127;
		else if(vexRT[Btn5D])
			motor[intakeHigh] = 0;

		if(vexRT[Btn6D])
		{
			motor[leftFront]  = 0;
			motor[leftBack]   = 0;
			motor[rightFront] = 0;
			motor[rightBack] = 0;
		}
		else if(vexRT[Btn8D])
		{
			motor[rightFront] = 127;
			motor[rightBack] = 127;
			motor[leftFront] = 127;
			motor[leftBack] = 127;
			wait1Msec(1000);
			motor[rightFront] = low;
			motor[rightBack] = low;
			motor[leftFront] = low;
			motor[leftBack] = low;
		}
		else if(vexRT[Btn6U])
		{
			motor[rightFront] = 127;
			motor[rightBack] = 127;
			motor[leftFront] = 127;
			motor[leftBack] = 127;
			wait1Msec(1000);
			motor[leftFront]  = slow;
			motor[leftBack]   = slow;
			motor[rightFront] = slow;
			motor[rightBack] = slow;
		}
		else if(vexRT[Btn8U])
		{
			motor[rightFront] = 127;
			motor[rightBack] = 127;
			motor[leftFront] = 127;
			motor[leftBack] = 127;
			wait1Msec(1000);
			motor[leftFront] = med;
			motor[leftBack] = med;
			motor[rightFront] = med;
			motor[rightBack] = med;
		}
		else if(vexRT[Btn8L])
		{
			motor[rightFront] = 127;
			motor[rightBack] = 127;
			motor[leftFront] = 127;
			motor[leftBack] = 127;
			wait1Msec(1000);
			motor[rightFront] = fast;
			motor[rightBack] = fast;
			motor[leftFront] = fast;
			motor[leftBack] = fast;
		}
		
		if(SensorValue[limitSwitch])
		{
			wait1Msec(500);
			motor[intakeHigh] = 0;
			motor[intakeLow] = 0;
		}

		SensorValue[LED] = RPM_Right_FlyWheel > DESIRED_RPM_FLYWHEEL && RPM_Left_FlyWheel > DESIRED_RPM_FLYWHEEL;
		
		if(RPM_Right_Motor >= 100)
			clearLCDLine(1);
		if(RPM_Left_Motor >= 100)
			clearLCDLine(1);

		if(nLCDButtons == leftButton)
		{
			left = true;
			center = false;
			right = false;
		}
		else if(nLCDButtons == centerButton)
		{
			left = false;
			center = true;
			right = false;
		}
		else if(nLCDButtons == rightButton)
		{
			left = false;
			center = false;
			right = true;
		}

		if(left)
		{
			displayLCDCenteredString(0, "Left   Right");
			displayLCDNumber(1, 0, left_encoder);
			displayLCDNumber(1, 8, right_encoder);
		}
		else if(center)
		{
			displayLCDCenteredString(0, "Left   Right");
			displayLCDNumber(1, 0, RPM_Left_Motor);
			displayLCDNumber(1, 8, RPM_Right_Motor);
		}
		else if(right)
		{
			displayLCDCenteredString(0, "Main   Backup");
			displayLCDNumber(1, 0, mainBattery);
			displayLCDNumber(1, 8, backupBattery);
		}
	}
}
