#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  shaftEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  shaftEncoderRight, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intakeHigh,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intakeLow,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

#define DESIRED_RPM_MOTOR 107
#define DESIRED_RPM_FLYWHEEL 1928

#define kP	0.02
#define kI	0.04

double RPM_Right_Motor;
double RPM_Left_Motor;

double RPM_Right_FlyWheel;
double RPM_Left_FlyWheel;

double speed_Right = 0;
double speed_Left = 0;

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	int speed = 85;

	motor[leftBack]   = speed;
	motor[leftFront]  = speed;
	motor[rightFront] = speed;
	motor[rightBack]  = speed;
	
	wait1Msec(2500);
	
	motor[intakeLow]  = 127;
	motor[intakeHigh] = 127;

	wait1Msec(100000);

	motor[leftBack]   = 0;
	motor[leftFront]  = 0;
	motor[rightFront] = 0;
	motor[rightBack]  = 0;

	motor[intakeLow]  = 0;
	motor[intakeHigh] = 0;
}

/*

Right Joystick: Drive right motors
Left Joystick: Drive left motors

Button 7U: Low intake
Button 7L: Low intake reverse
Button 7D: Low intake off

Button 5U: High intake
Button 7R: reverse
Button 5D: High intake off

Button 6D - flywheels off
Button 8D - flywheels 50
Button 6U - flywheels 70
Button 8U - flywheels 90
Button 8L - flywheels 120

*/

task adjustPower()
{
	double pidError_Right = 0;
	double pidIntegral_Right = 0;
	double pidValue_Right;

	double pidError_Left = 0;
	double pidIntegral_Left = 0;
	double pidValue_Left;
	
	pidError_Right = DESIRED_RPM_FLYWHEEL - RPM_RIGHT_FLYWHEEL;
	pidError_Left = DESIRED_RPM_FLYWHEEL - RPM_LEFT_FLYWHEEL;

	if(pidError_Right < 50)
		pidIntegral_Right += pidError_Right;
	else
		pidIntegral_Right = 0;

	if(pidError_Left < 50)
		pidIntegral_Left += pidError_Left;
	else
		pidIntegral_Left = 0;
	
	pidValue_Right = (kP * pidError_Right) + (kI * pidIntegral_Right);
	speed += pidValue_Right;

	pidValue_Left = (kP * pidError_Left) + (kI * pidIntegral_Left);
	speed += pidValue_Left;
	
	if(speed_Right > 127)
		speed_Right = 127;
	else if(speed_Right < -127)
		speed_Right = -127;

	if(speed_Left > 127)
		speed_Left = 127;
	else if(speed_Left < -127)
		speed_Left = -127;

	motor[rightFront]   = speed_Right;
	motor[rightBack] = speed_Right;

	motor[leftFront]   = speed_Left;
	motor[leftBack] = speed_Left;
}

task usercontrol()
{
	int fast = 120;
	int med = 90;
	int slow = 70;
	int low = 50;
	
	
	resetMotorEncoder(leftBack);
	resetMotorEncoder(rightBack);
	
	clearLCDLine(0);
	displayLCDCenteredString(0, "Left   Right");
	
	while(true)
	{
		RPM_Right_Motor = getMotorVelocity(rightBack);
		RPM_Right_FlyWheel = RPM_Right_Motor * 18;

		RPM_Left_Motor = getMotorVelocity(leftBack);
		RPM_Left_FlyWheel = RPM_Left_Motor * 18;

		motor[LeftDrive] = vexRT[Ch3];
		motor[RightDrive] = vexRT[Ch2];

		if(vexRT[Btn7U])
			motor[intakeLow] = 127;
		else if(vexRT[Btn7L])
			motor[intakeLow] = -127;
		else if(vexRT[Btn7D])
			motor[intakeLow] = 0;

		if(vexRT[Btn5U])
			motor[intakeHigh] = 127;
		else if(vexRT[Btn7R])
			motor[intakeHigh] = -127;
		else if(vexRT[Btn5D])
			motor[intakeHigh] = 0;

		if(vexRT[Btn6D])
		{
			motor[leftFront]  = 0;
			motor[leftBack]   = 0;
			motor[rightFront] = 0;
			motor[rightBack] = 0;
		}
		else if(vexRT[Btn8D])
		{
			motor[rightFront] = low;
			motor[rightBack] = low;
			motor[leftFront] = low;
			motor[leftBack] = low;
		}
		else if(vexRT[Btn6U])
		{
			motor[leftFront]  = slow;
			motor[leftBack]   = slow;
			motor[rightFront] = slow;
			motor[rightBack] = slow;
		}
		else if(vexRT[Btn8U])
		{
			motor[leftFront] = med;
			motor[leftBack] = med;
			motor[rightFront] = med;
			motor[rightBack] = med;
		}
		else if(vexRT[Btn8L])
		{
			motor[rightFront] = fast;
			motor[rightBack] = fast;
			motor[leftFront] = fast;
			motor[leftBack] = fast;
		}
		else if(vexRT[Btn8R])
			StartTask(adjustPower());

		SensorValue[LED] = RPM_Right_FlyWheel > DESIRED_RPM_FLYWHEEL && RPM_Left_FlyWheel > DESIRED_RPM_FLYWHEEL;
		
		clearLCDLine(1);
		displayLCDNumber(1, 0, RPM_Left_FlyWheel);
		displayLCDNumber(1, 8, RPM_Right_FlyWheel);
	}
}